# Generated by Django 3.2 on 2021-10-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=20)),
                ('father_name', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(default=datetime.datetime(2021, 10, 27, 13, 20, 9, 67321), max_length=10)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=15)),
                ('pin', models.IntegerField(default='')),
                ('mobile', models.BigIntegerField(default='')),
                ('email', models.EmailField(max_length=30)),
                ('class_opted', models.CharField(choices=[('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], max_length=2)),
                ('marks', models.CharField(default='', max_length=3)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
